/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ResumeId = IDL.Text;
export const SessionToken = IDL.Text;
export const MatchId = IDL.Text;
export const Timestamp = IDL.Int;
export const MatchRecord = IDL.Record({
  'id' : MatchId,
  'jobDescription' : IDL.Text,
  'matchScore' : IDL.Nat,
  'resumeName' : IDL.Text,
  'resumeId' : ResumeId,
  'missingSkills' : IDL.Vec(IDL.Text),
  'matchedSkills' : IDL.Vec(IDL.Text),
  'matchDate' : Timestamp,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Resume = IDL.Record({
  'id' : ResumeId,
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
  'score' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
  'uploadDate' : Timestamp,
  'uploadedBy' : IDL.Text,
});
export const UserSummary = IDL.Record({
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const LoginSuccess = IDL.Record({
  'token' : SessionToken,
  'role' : IDL.Text,
});
export const LoginError = IDL.Variant({ 'invalidCredentials' : IDL.Null });
export const LoginResult = IDL.Variant({
  'ok' : LoginSuccess,
  'err' : LoginError,
});
export const MatchResult = IDL.Variant({
  'ok' : MatchRecord,
  'err' : IDL.Text,
});
export const RegisterError = IDL.Variant({
  'invalidInput' : IDL.Null,
  'duplicateEmail' : IDL.Null,
});
export const RegisterResult = IDL.Variant({
  'ok' : LoginSuccess,
  'err' : RegisterError,
});
export const ResumeResult = IDL.Variant({ 'ok' : Resume, 'err' : IDL.Text });
export const SessionResult = IDL.Variant({
  'ok' : LoginSuccess,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'computeScore' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], ['query']),
  'deleteResume' : IDL.Func([IDL.Text, ResumeId], [IDL.Bool], []),
  'deleteUser' : IDL.Func(
      [SessionToken, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'extractSkillsFromText' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchHistory' : IDL.Func([], [IDL.Vec(MatchRecord)], ['query']),
  'getResumeMatchHistory' : IDL.Func(
      [ResumeId],
      [IDL.Vec(MatchRecord)],
      ['query'],
    ),
  'getResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getSecurityQuestion' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getUserResumes' : IDL.Func([IDL.Text], [IDL.Vec(Resume)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func(
      [SessionToken],
      [IDL.Variant({ 'ok' : IDL.Vec(UserSummary), 'err' : IDL.Text })],
      [],
    ),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([SessionToken], [IDL.Bool], []),
  'matchResume' : IDL.Func([IDL.Text, ResumeId, IDL.Text], [MatchResult], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
  'resetPasswordBySecurityQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSecurityQuestion' : IDL.Func(
      [SessionToken, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadResume' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [ResumeResult],
      [],
    ),
  'validateSession' : IDL.Func([SessionToken], [SessionResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ResumeId = IDL.Text;
  const SessionToken = IDL.Text;
  const MatchId = IDL.Text;
  const Timestamp = IDL.Int;
  const MatchRecord = IDL.Record({
    'id' : MatchId,
    'jobDescription' : IDL.Text,
    'matchScore' : IDL.Nat,
    'resumeName' : IDL.Text,
    'resumeId' : ResumeId,
    'missingSkills' : IDL.Vec(IDL.Text),
    'matchedSkills' : IDL.Vec(IDL.Text),
    'matchDate' : Timestamp,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Resume = IDL.Record({
    'id' : ResumeId,
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
    'score' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
    'uploadDate' : Timestamp,
    'uploadedBy' : IDL.Text,
  });
  const UserSummary = IDL.Record({
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const LoginSuccess = IDL.Record({
    'token' : SessionToken,
    'role' : IDL.Text,
  });
  const LoginError = IDL.Variant({ 'invalidCredentials' : IDL.Null });
  const LoginResult = IDL.Variant({ 'ok' : LoginSuccess, 'err' : LoginError });
  const MatchResult = IDL.Variant({ 'ok' : MatchRecord, 'err' : IDL.Text });
  const RegisterError = IDL.Variant({
    'invalidInput' : IDL.Null,
    'duplicateEmail' : IDL.Null,
  });
  const RegisterResult = IDL.Variant({
    'ok' : LoginSuccess,
    'err' : RegisterError,
  });
  const ResumeResult = IDL.Variant({ 'ok' : Resume, 'err' : IDL.Text });
  const SessionResult = IDL.Variant({ 'ok' : LoginSuccess, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'computeScore' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], ['query']),
    'deleteResume' : IDL.Func([IDL.Text, ResumeId], [IDL.Bool], []),
    'deleteUser' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'extractSkillsFromText' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchHistory' : IDL.Func([], [IDL.Vec(MatchRecord)], ['query']),
    'getResumeMatchHistory' : IDL.Func(
        [ResumeId],
        [IDL.Vec(MatchRecord)],
        ['query'],
      ),
    'getResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getSecurityQuestion' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getUserResumes' : IDL.Func([IDL.Text], [IDL.Vec(Resume)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func(
        [SessionToken],
        [IDL.Variant({ 'ok' : IDL.Vec(UserSummary), 'err' : IDL.Text })],
        [],
      ),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([SessionToken], [IDL.Bool], []),
    'matchResume' : IDL.Func([IDL.Text, ResumeId, IDL.Text], [MatchResult], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
    'resetPasswordBySecurityQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSecurityQuestion' : IDL.Func(
        [SessionToken, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadResume' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [ResumeResult],
        [],
      ),
    'validateSession' : IDL.Func([SessionToken], [SessionResult], []),
  });
};

export const init = ({ IDL }) => { return []; };