/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type LoginError = { 'invalidCredentials' : null };
export type LoginResult = { 'ok' : LoginSuccess } |
  { 'err' : LoginError };
export interface LoginSuccess { 'token' : SessionToken, 'role' : string }
export type MatchId = string;
export interface MatchRecord {
  'id' : MatchId,
  'jobDescription' : string,
  'matchScore' : bigint,
  'resumeName' : string,
  'resumeId' : ResumeId,
  'missingSkills' : Array<string>,
  'matchedSkills' : Array<string>,
  'matchDate' : Timestamp,
}
export type MatchResult = { 'ok' : MatchRecord } |
  { 'err' : string };
export type RegisterError = { 'invalidInput' : null } |
  { 'duplicateEmail' : null };
export type RegisterResult = { 'ok' : LoginSuccess } |
  { 'err' : RegisterError };
export interface Resume {
  'id' : ResumeId,
  'blob' : ExternalBlob,
  'filename' : string,
  'score' : bigint,
  'skills' : Array<string>,
  'uploadDate' : Timestamp,
  'uploadedBy' : string,
}
export type ResumeId = string;
export type ResumeResult = { 'ok' : Resume } |
  { 'err' : string };
export type SessionResult = { 'ok' : LoginSuccess } |
  { 'err' : string };
export type SessionToken = string;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'createdAt' : bigint,
  'role' : string,
  'email' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'computeScore' : ActorMethod<[Array<string>], bigint>,
  'deleteResume' : ActorMethod<[string, ResumeId], boolean>,
  'deleteUser' : ActorMethod<
    [SessionToken, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'extractSkillsFromText' : ActorMethod<[string], Array<string>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchHistory' : ActorMethod<[], Array<MatchRecord>>,
  'getResumeMatchHistory' : ActorMethod<[ResumeId], Array<MatchRecord>>,
  'getResumes' : ActorMethod<[], Array<Resume>>,
  'getSecurityQuestion' : ActorMethod<[string], [] | [string]>,
  'getUserResumes' : ActorMethod<[string], Array<Resume>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<
    [SessionToken],
    { 'ok' : Array<UserSummary> } |
      { 'err' : string }
  >,
  'login' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[SessionToken], boolean>,
  'matchResume' : ActorMethod<[string, ResumeId, string], MatchResult>,
  'register' : ActorMethod<[string, string], RegisterResult>,
  'resetPasswordBySecurityQuestion' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSecurityQuestion' : ActorMethod<
    [SessionToken, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadResume' : ActorMethod<[string, string, ExternalBlob], ResumeResult>,
  'validateSession' : ActorMethod<[SessionToken], SessionResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];